$(function(){
    $("li#zerotab").mouseenter(function(){
        $("li#zerotab").addClass("navmenu")
    });

    $("li#firsttab").mouseenter(function(){
        $("li#firsttab").addClass("navmenu")
    });
    $("li#secondtab").mouseenter(function(){
        $("li#secondtab").addClass("navmenu")
    });
    $("li#thirdtab").mouseenter(function(){
        $("li#thirdtab").addClass("navmenu")
    });
    $("li#fourthtab").mouseenter(function(){
        $("li#fourthtab").addClass("navmenu")
    });
    $("li#fifthtab").mouseenter(function(){
        $("li#fifthtab").addClass("navmenu")
    });
    $("div.navbar-header#main").mouseenter(function(){
        $("div.navbar-header#main").addClass("main_tab_color")
    });
})
$(function(){
    $("li").mouseout(function(){
        $("li").removeClass("navmenu");
    });

    $("div.navbar-header#main").mouseout(function(){
        $("div.navbar-header#main").removeClass("main_tab_color");
    });
})